### ISSUE TITLE
(MC 1.20.1) The new version of zombies reworked has a faulty data config, causing a crash when relaunching the game.

### ISSUE THREAD

**Issue by Yokisan249** [TheASEStefan/ZombiesReworkedMod#2]
After booting up the game the config generates with no issues BUT, when restarting the game it immediately crashes and says "net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file ZombiesReworked-data.toml of type COMMON for modid zombies_reworked"

[crash-2023-12-29_15.34.22-client.txt](https://github.com/TheASEStefan/ZombiesReworkedMod/files/13795531/crash-2023-12-29_15.34.22-client.txt)

**Comment by Yokisan249** [comment]
I think it might be this part of the config:

["Armor Info"]
	#Default true
	"Should zombies spawn with more armor and tools and more commonly" = true

	["Armor Info"."What is the chance of zombies spawning with more armor and tools? The bigger the number, the smaller the chance"]
		#Default 160
		#Range: 100 ~ 1000
		 = 160

**Comment by Yokisan249** [comment]
I think it might be because theres no "" before the "= 160"
	["Armor Info"."What is the chance of zombies spawning with more armor and tools? The bigger the number, the smaller the chance"]
		#Default 160
		#Range: 100 ~ 1000
		 = 160

**Comment by TheASEStefan** [comment]
Yeah I saw that bug too, it's a small config bug but I will try to fix it either way when I have time.

**Comment by zanyahtzee** [comment]
Does the issue persist on an older version of the mod (1.0.2) for 1.20.1?

**Comment by Yokisan249** [comment]
> Does the issue persist on an older version of the mod (1.0.2) for 1.20.1?

Yeah, the issue persists and its a data config issue. If you try to fix it yourself it will make minecraft boot up like usual BUT the config will reset again and it can make your world crash. So don't risk it until the dev fixes it (use the previous version).

**Comment by festro** [comment]
I'm having this issue on 1.19.2, deleting data config lets me launch again but have to do it every time otherwise crash.

**Comment by TheASEStefan** [comment]
error fixed, version is up!

**Comment by festro** [comment]
Thanks, issue fixed for me.
