### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by solonovamax** [TheASEStefan/ZombiesReworkedMod#6]
On modrinth, as well as in the `mods.toml` file, this mod is marked as being MIT licensed, however there exists no `LICENSE` file in the root of the repository.

**Comment by TheASEStefan** [comment]
I deleted it perhaps. But why was it so important if I may ask? After all, the license in the mods.toml, like you said, curseforge, modrinth, github, etc.

**Comment by solonovamax** [comment]
technically, unless you actually place the `LICENSE` file in the repository, the code is not under that license. or at least, it's debatable that it's not.

**Comment by TheASEStefan** [comment]
You see, that is not quite correct. The "LICENSE" you are talking about is a file generated by Forge. It doesn't refer to you in any way. Plus, the code can only be viewed on GitHub in which the repository has the "MIT License" license.

**Comment by solonovamax** [comment]
> It doesn't refer to you in any way. Plus, the code can only be viewed on GitHub in which the repository has the "MIT License" license.

no, that is not true.

to quote the MIT license,
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

as such, it is necessary to include the entire MIT license text.

> The "LICENSE" you are talking about is a file generated by Forge.

Placing it in a `LICENSE` file is standard convention. Not just one adopted from forge, but one that is standard throughout effectively all open source software. Either to use `LICENSE`, `LICENSE.txt`, `LICENSE.md`, `LICENSE.rst`, or a `LICENSE` file with some other extension. (Though no extension is the most common)

According to the OSI foundation, here are the following guidelines to follow when applying an open source license: https://producingoss.com/en/license-quickstart.html#license-quickstart-applying (See: [How do I apply <SOME OPEN SOURCE LICENSE> to software I'm releasing?](https://opensource.org/faq#apply-license). Specifically, the last sentence of the first paragraph.)
It notes:

> Once you've chosen a license, you'll need to apply it to the software.
>
> The first thing to do is state the license clearly on the project's front page. You don't need to include the actual text of the license there; just give its name and make it link to the full license text on another page. That tells the public what license you intend the software to be released under — but it's not quite sufficient for legal purposes. The other step is that the software itself should include the license.
>
> The standard way to do this is to put the full license text in a file called LICENSE (or COPYING) included with the source code, and then at the top of each source file put a short notice in a comment, naming the copyright date, holder, and license, and saying where to find the full text of the license.
>
> There are many variations on this pattern, so we'll look at just one example here. The GNU GPL says to put a notice like this at the top of each source file:
> 
> > Copyright (C) <year> <name of author>
> >
> > This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
> > 
> > This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
> > 
> > You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>
> 
> It does not say specifically that the copy of the license you received along with the program is in the file COPYING or LICENSE, but that's where it's usually put. (You could change the above notice to state that directly, but there's no real need to.)
> 
> In general, the notice you put in each source file does not have to look exactly like the one above, as long as it starts with the same notice of copyright holder and date<sup>[[28]](https://producingoss.com/en/license-quickstart.html#ftn.idp700)</sup>, states the name of the license, and makes clear where to view the full license terms. It's always best to consult a lawyer, of course, if you can afford one.

You should generally include the full license text somewhere in the repository, as noted by "That tells the public what license you intend the software to be released under — but it's not quite sufficient for legal purposes. The other step is that the software itself should include the license."

**Comment by TheASEStefan** [comment]
Do you atleast know who Kaupenjoe is? Well assuming you do know, he doesn't include a license in his source code and doing that is almost pointless. As I said, the license you start with when extracting a forge mdk and creating a minecraft mod is from FORGE. It's not yours bruh. I've seen tons of Minecraft mods, actually almost all not having a license in their source code. It's pointless when you have it on github but also on your mod pages. Why didn't you bother to talk with them instead of me lol. Also I don't see you create your very own proiect from zero, and I don't mean that creating it as a contributor, I meant to create one as an author all alone from zero. 
With that being said, the only people who specify the license in their code are the ones who just want to make their code "special", seeminglessly putting it there to show if you can take their work or not, which is bs if your project already mentions that on it's main page.

**Comment by solonovamax** [comment]
> Do you atleast know who Kaupenjoe is?

I don't see how that's relevant.

> Well assuming you do know, he doesn't include a license in his source code and doing that is almost pointless.

Not including the `LICENSE` file in your repository makes it so that the license is in a legally ambiguous state. No, it is not pointless.

> As I said, the license you start with when extracting a forge mdk and creating a minecraft mod is from FORGE.

Yes, there is a license provided for you with the forge MDK, however you can also add your own license, such as the Apache 2.0 license, the GPLv3, the BSD license, or many more. It only includes the MIT license as an example.

> I've seen tons of Minecraft mods, actually almost all not having a license in their source code. It's pointless when you have it on github but also on your mod pages.

The vast majority of major open source minecraft mods have a `LICENSE` file.

> Why didn't you bother to talk with them instead of me lol.

I don't see how that's relevant.

> Also I don't see you create your very own proiect from zero, and I don't mean that creating it as a contributor, I meant to create one as an author all alone from zero

I have MANY open source projects that I have authored ENTIRELY by myself.
Here are a few examples:
- Everything under the [solo-studios](https://github.com/solo-studios) github org. (this is my org which I created.)
- [BeaconOverhaulReloaded](https://github.com/solonovamax/BeaconOverhaulReloaded), which although it is a fork, I have effectively rewritten everything myself at this point.
- [solonovamax.gay](https://github.com/solonovamax/solonovamax.gay)
- [Omnivox-Scraper](https://github.com/solonovamax/Omnivox-Scraper)

And, I'm only counting here things that I consider major projects. There are many others that I did not include.

> With that being said, the only people who specify the license in their code are the ones who just want to make their code "special", seeminglessly putting it there to show if you can take their work or not, which is bs if your project already mentions that on it's main page.

What?

This is industry standard. And for a reason.

Here, let's go through a few major open source projects:

- The linux kernel? there's a file called `COPYING`.
- Any of the repositories for fabric? `LICENSE` and `HEADER`.
- Forge? `LICENSE.txt` and `LICENSE-header.txt`.
- neoforge? `LICENSE.txt`.
- react? `LICENSE`.
- node.js? `LICENSE`.
- OBS? `COPYING`
- guava? `LICENSE`.
- vscode? `LICENSE.txt`.
- typescript? `LICENSE.txt`. 
- git? `COPYING` and `LGPL-2.1`.
- KDE? `COPYING`, (sometimes also `COPYING-CMAKE-SCRIPTS`, or a `LICENSES` directory)

I can go on and on.

**Comment by TheASEStefan** [comment]
> > Do you atleast know who Kaupenjoe is?
> 
> I don't see how that's relevant.
First of all, you should think this is very relevant, not only he is a big and known modder, maybe modding for more time than you even. But he is making TUTORIALS which means that most of the people who started modding, watched him, and he never yaps about a license like you do. He does in fact mention stuff about the license, but only modifying in the game files, like the .toml file, or the github page and curseforge and whatever. You thinking this is not relevant is my main issue here. How do you expect everyone to have a "special license" when their code specifies the rest. Nonetheless, this discussion is going nowhere and I don't see why you don't just mind your business, you are a walking rage bait dude, cut it off.
> 
> > Well assuming you do know, he doesn't include a license in his source code and doing that is almost pointless.
> 
> Not including the `LICENSE` file in your repository makes it so that the license is in a legally ambiguous state. No, it is not pointless.
> 

That's not true at all, I can mention multiple Minecraft mods that don't have a special license file in their code, but have marked their repository as having a special one. You just aren't looking where you should.

> > As I said, the license you start with when extracting a forge mdk and creating a minecraft mod is from FORGE.
> 
> Yes, there is a license provided for you with the forge MDK, however you can also add your own license, such as the Apache 2.0 license, the GPLv3, the BSD license, or many more. It only includes the MIT license as an example.

That's different though. A modding framework != a mod on it's own. I don't see where it says specifically to add a license, I just don't get it... what is with people and putting their mark on everything. It strictly says your license name wherever you go, on any site that includes the software!
> 
> > I've seen tons of Minecraft mods, actually almost all not having a license in their source code. It's pointless when you have it on github but also on your mod pages.

It's really not pointless, it's even the other way around since it's more common for people to look at your license on your mod page, or the github repo, a thing which even Kaupenjoe did in one of his videos.
> 
> The vast majority of major open source minecraft mods have a `LICENSE` file.
> 
> > Why didn't you bother to talk with them instead of me lol.
> 
> I don't see how that's relevant.
It's relevant since you opened this as an "issue" on github. Do you just stay in home all day looking at whether or not people have license files in their repo? 
> 
> > Also I don't see you create your very own proiect from zero, and I don't mean that creating it as a contributor, I meant to create one as an author all alone from zero
> 
> I have MANY open source projects that I have authored ENTIRELY by myself. Here are a few examples:
> 
> * Everything under the [solo-studios](https://github.com/solo-studios) github org. (this is my org which I created.)
> * [BeaconOverhaulReloaded](https://github.com/solonovamax/BeaconOverhaulReloaded), which although it is a fork, I have effectively rewritten everything myself at this point.
> * [solonovamax.gay](https://github.com/solonovamax/solonovamax.gay)
> * [Omnivox-Scraper](https://github.com/solonovamax/Omnivox-Scraper)
> 
> And, I'm only counting here things that I consider major projects. There are many others that I did not include.
> 
> > With that being said, the only people who specify the license in their code are the ones who just want to make their code "special", seeminglessly putting it there to show if you can take their work or not, which is bs if your project already mentions that on it's main page.
> 
> What?
> 
> This is industry standard. And for a reason.
> 
> Here, let's go through a few major open source projects:
> 
> * The linux kernel? there's a file called `COPYING`.
> * Any of the repositories for fabric? `LICENSE` and `HEADER`.
> * Forge? `LICENSE.txt` and `LICENSE-header.txt`.
> * neoforge? `LICENSE.txt`.
> * react? `LICENSE`.
> * node.js? `LICENSE`.
> * OBS? `COPYING`
> * guava? `LICENSE`.
> * vscode? `LICENSE.txt`.
> * typescript? `LICENSE.txt`.
> * git? `COPYING` and `LGPL-2.1`.
> * KDE? `COPYING`, (sometimes also `COPYING-CMAKE-SCRIPTS`, or a `LICENSES` directory)
> 
> I can go on and on.

That's really unimportant. And may I add that I am a single coder, these softwares have licenses and stuff because there is one guy taking care of that, while another is coding the actual thing, and that's facts most of the time. I don't know about you, but if I see that my software is licensed on any website that is added on, that's enough. No need for "overmarking"

**Comment by solonovamax** [comment]
> > > I've seen tons of Minecraft mods, actually almost all not having a license in their source code. It's pointless when you have it on github but also on your mod pages.
> 
> It's really not pointless, it's even the other way around since it's more common for people to look at your license on your mod page, or the github repo, a thing which even Kaupenjoe did in one of his videos.

you do realize you're just replying to yourself there, right?

**Comment by solonovamax** [comment]
> First of all, you should think this is very relevant, not only he is a big and known modder, maybe modding for more time than you even. But he is making TUTORIALS which means that most of the people who started modding, watched him, and he never yaps about a license like you do. He does in fact mention stuff about the license, but only modifying in the game files, like the .toml file, or the github page and curseforge and whatever. You thinking this is not relevant is my main issue here. How do you expect everyone to have a "special license" when their code specifies the rest. Nonetheless, this discussion is going nowhere and I don't see why you don't just mind your business, you are a walking rage bait dude, cut it off.

ok, and? the reason he doesn't explain it is because he isn't expecting people to make their first mod open source lmfao, and also expects people to read basic things such as [Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) from docs.github.com before attempting to do so lol

also, no, I've been writing mods since like 2016.

also also, this isn't a "special license". it's literally one of the most common licenses out there. it's just common practice to put it in a `LICENSE` or `COPYING` file, otherwise your project could quite easily be considered ARR. (so, it isn't open source)

> That's not true at all, I can mention multiple Minecraft mods that don't have a special license file in their code, but have marked their repository as having a special one. You just aren't looking where you should.

then go ahead. and, please, do only mention large mods.

> And may I add that I am a single coder

it is incredibly simple to add a `LICENSE` file. literally just go to https://mit-license.org, copy that text into a `LICENSE` file and then change `<copyright holders>` to your name 💀

**Comment by TheASEStefan** [comment]
Bro why are you so pressed even 💀
And you are actually unaware of the fact that Kaupenjoe suggests for you to have an open source code 💀💀💀 So why say things that you are not aware of? Spore and From the Shadows don't have a license, neither does MrCrayfish since it only has a forge one 💀💀💀. I can name so muxh

**Comment by herrnn** [comment]
Having no license is not a good practice but in a small project it don't really matter that much. IMO, just give it a MIT licenses and call it a day. leaving as is make the legal implication ambiguous, having some kind of license protect you the Modder (as people can sue you in some weird case) as well as other people (who fork your code). As licenses in Curseforge does not imply the legality of the source code. just the jar provided through Curseforge.

also actually MrCrayfish do have license an MIT license.
